### PR TITLE
Programmatically dismiss any CFAlertDialog

### PR DESCRIPTION
**Pull request by jeremypele**
Included
```
- Ability to programmatically dismiss any alert
- Fix cancellable boolean option on ios
- Various refactoring/code simplification 
```

Cheers 🎉 😄

### CODE REVIEW

**Comment by shiv19** [comment]
@jeremypele are any changes required in readme file after merging this?

**Comment by jeremypele** [comment]
@shiv19 Yup just did!

**Comment by shiv19** [comment]
Thanks! I'll publish it tonight

**Comment by jeremypele** [comment]
Fast! 🔥

**Comment by shiv19** [comment]
Published as version 1.0.9

**Comment by jeremypele** [comment]
With the last version published, I'm facing an issue with the podfile though:
moving `pod 'CFAlertViewController', '~> 3.0'` to `pod 'CFAlertViewController'` seem to fix it.

Do you have the same behaviour on your side?

**Comment by shiv19** [comment]
maybe, I'll just push a new version that changes `pod 'CFAlertViewController', '~> 3.0'` to `pod 'CFAlertViewController'`

**Comment by shiv19** [comment]
published as 1.0.10

**Pull request merged**
